# Generated by Django 4.0.5 on 2022-06-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_klienta', models.CharField(max_length=180)),
                ('jmeno', models.CharField(max_length=180)),
                ('prijmeni', models.CharField(max_length=180)),
                ('narozeni', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_smlouvy', models.CharField(max_length=180)),
                ('pojisteni', models.CharField(max_length=180)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_klienta', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=180)),
                ('kontakt', models.CharField(max_length=180)),
                ('adresa', models.CharField(max_length=200)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.klient')),
            ],
        ),
    ]
