# Generated by Django 4.0.5 on 2022-06-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienti'},
        ),
        migrations.AlterModelOptions(
            name='kontakt',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakty'},
        ),
        migrations.AlterModelOptions(
            name='pojisteni',
            options={'verbose_name': 'Pojištění', 'verbose_name_plural': 'Pojištění'},
        ),
        migrations.RemoveField(
            model_name='kontakt',
            name='klient',
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='klient',
        ),
        migrations.AddField(
            model_name='klient',
            name='kontakt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaze.kontakt'),
        ),
        migrations.AddField(
            model_name='klient',
            name='pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaze.pojisteni'),
        ),
    ]
