# Generated by Django 4.0.5 on 2022-06-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0002_alter_klient_options_alter_kontakt_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='id_smlouvy',
        ),
    ]
