# Generated by Django 4.0.5 on 2022-06-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0004_remove_klient_kontakt_kontakt_klient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontakt',
            name='id_klienta',
        ),
    ]
