# Generated by Django 4.0.5 on 2022-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0006_uzivatel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DruhPojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojisteni_druh', models.CharField(max_length=180, verbose_name='Pojištění')),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
        migrations.AddField(
            model_name='klient',
            name='pojisteni_druh',
            field=models.ManyToManyField(to='databaze.druhpojisteni'),
        ),
    ]
