# Generated by Django 4.0.5 on 2022-06-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0007_druhpojisteni_klient_pojisteni_druh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='pojisteni',
        ),
        migrations.DeleteModel(
            name='Pojisteni',
        ),
    ]
