# Generated by Django 4.0.5 on 2022-06-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0008_remove_klient_pojisteni_delete_pojisteni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DruhPojisteni',
            new_name='Pojisteni',
        ),
        migrations.RenameField(
            model_name='klient',
            old_name='pojisteni_druh',
            new_name='pojisteni',
        ),
        migrations.RenameField(
            model_name='pojisteni',
            old_name='pojisteni_druh',
            new_name='pojisteni_title',
        ),
    ]
